/*
 await prisma.meal.createMany({
    data: [
      // Śniadania
      {
        title: 'Pożywna Owsianka z Owocami',
        description: 'Klasyczna owsianka z dodatkiem świeżych owoców i orzechów.',
        kcal: 350,
        carbohydrates: 55,
        protein: 10,
        fat: 8,
        preparation: 'Gotuj płatki owsiane w mleku, dodaj pokrojone owoce i orzechy.',
        ingredients: ['Płatki owsiane', 'Mleko', 'Jagody', 'Banan', 'Orzechy', 'Miód'],
        type: MealType.BREAKFAST,
      },
      {
        title: 'Jajecznica z Warzywami',
        description: 'Jajecznica z papryką, pomidorami i cebulą.',
        kcal: 300,
        carbohydrates: 15,
        protein: 20,
        fat: 18,
        preparation: 'Smaż jajka z pokrojonymi warzywami na patelni.',
        ingredients: ['Jaja', 'Papryka', 'Pomidory', 'Cebula', 'Oliwa z oliwek'],
        type: MealType.BREAKFAST,
      },
      {
        title: 'Smoothie Bananowo-Szpinakowe',
        description: 'Smoothie z banana i świeżego szpinaku.',
        kcal: 250,
        carbohydrates: 40,
        protein: 5,
        fat: 4,
        preparation: 'Blenduj banana, szpinak i jogurt naturalny.',
        ingredients: ['Banan', 'Szpinak', 'Jogurt naturalny'],
        type: MealType.BREAKFAST,
      },
      {
        title: 'Tosty z Awokado i Jajkiem',
        description: 'Tosty z pastą z awokado i gotowanym jajkiem.',
        kcal: 320,
        carbohydrates: 30,
        protein: 15,
        fat: 18,
        preparation: 'Posmaruj tosty pastą z awokado i dodaj pokrojone jajko.',
        ingredients: ['Chleb pełnoziarnisty', 'Awokado', 'Jajko', 'Sól', 'Pieprz'],
        type: MealType.BREAKFAST,
      },
      // Drugie Śniadania
      {
        title: 'Jogurt z Musli i Owocami',
        description: 'Jogurt naturalny z musli i świeżymi owocami.',
        kcal: 300,
        carbohydrates: 40,
        protein: 10,
        fat: 8,
        preparation: 'Wymieszaj jogurt z musli i dodaj pokrojone owoce.',
        ingredients: ['Jogurt naturalny', 'Musli', 'Owoce sezonowe'],
        type: MealType.SECOND_BREAKFAST,
      },
      {
        title: 'Kanapki z Chudą Wędliną i Warzywami',
        description: 'Kanapki z chudą wędliną, sałatą i pomidorami.',
        kcal: 280,
        carbohydrates: 35,
        protein: 15,
        fat: 10,
        preparation: 'Złóż wędlinę i warzywa między kromki chleba.',
        ingredients: ['Chleb pełnoziarnisty', 'Wędliny', 'Sałata', 'Pomidory', 'Ogórek'],
        type: MealType.SECOND_BREAKFAST,
      },
      {
        title: 'Sałatka Owocowa z Orzechami',
        description: 'Świeża sałatka owocowa z dodatkiem orzechów.',
        kcal: 250,
        carbohydrates: 35,
        protein: 5,
        fat: 12,
        preparation: 'Pokrój owoce i wymieszaj z orzechami.',
        ingredients: ['Owoce sezonowe', 'Orzechy'],
        type: MealType.SECOND_BREAKFAST,
      },
      {
        title: 'Chia Pudding z Owocami',
        description: 'Pudding chia z dodatkiem świeżych owoców.',
        kcal: 280,
        carbohydrates: 25,
        protein: 8,
        fat: 14,
        preparation: 'Wymieszaj nasiona chia z mlekiem i odstaw na kilka godzin, następnie dodaj owoce.',
        ingredients: ['Nasiona chia', 'Mleko', 'Owoce'],
        type: MealType.SECOND_BREAKFAST,
      },
      // Obiady
      {
        title: 'Kurczak w Sosie Pomidorowym z Ryżem',
        description: 'Soczysty kurczak w sosie pomidorowym podany z ryżem.',
        kcal: 450,
        carbohydrates: 60,
        protein: 35,
        fat: 12,
        preparation: 'Smaż kurczaka w sosie pomidorowym, podawaj z ugotowanym ryżem.',
        ingredients: ['Kurczak', 'Sos pomidorowy', 'Ryż', 'Przyprawy'],
        type: MealType.LUNCH,
      },
      {
        title: 'Sałatka Cezar z Kurczakiem',
        description: 'Klasyczna sałatka Cezar z grillowanym kurczakiem.',
        kcal: 400,
        carbohydrates: 20,
        protein: 30,
        fat: 22,
        preparation: 'Wymieszaj sałatę, kurczaka, grzanki i sos Cezar.',
        ingredients: ['Sałata', 'Grillowany kurczak', 'Grzanki', 'Sos Cezar'],
        type: MealType.LUNCH,
      },
      {
        title: 'Spaghetti Bolognese',
        description: 'Makaron spaghetti z klasycznym sosem bolognese.',
        kcal: 500,
        carbohydrates: 70,
        protein: 30,
        fat: 15,
        preparation: 'Gotuj makaron i sos bolognese, wymieszaj przed podaniem.',
        ingredients: ['Makaron spaghetti', 'Mięso mielone', 'Sos pomidorowy', 'Cebula', 'Przyprawy'],
        type: MealType.LUNCH,
      },
      {
        title: 'Kurczak Tandoori z Warzywami',
        description: 'Kurczak marynowany w przyprawach tandoori, pieczony z warzywami.',
        kcal: 450,
        carbohydrates: 25,
        protein: 35,
        fat: 20,
        preparation: 'Marynuj kurczaka w przyprawach tandoori, piecz z warzywami.',
        ingredients: ['Kurczak', 'Przyprawy tandoori', 'Warzywa (np. papryka, cukinia)'],
        type: MealType.LUNCH,
      },
      {
        title: 'Zupa Brokułowa z Grzankami',
        description: 'Kremowa zupa brokułowa podana z chrupiącymi grzankami.',
        kcal: 350,
        carbohydrates: 35,
        protein: 10,
        fat: 15,
        preparation: 'Gotuj brokuły, zmiksuj na krem, podawaj z grzankami.',
        ingredients: ['Brokuły', 'Cebula', 'Bulion', 'Grzanki'],
        type: MealType.LUNCH,
      },
      // Kolacje
      {
        title: 'Łosoś z Warzywami',
        description: 'Pieczony łosoś z mieszanką warzyw.',
        kcal: 400,
        carbohydrates: 20,
        protein: 30,
        fat: 20,
        preparation: 'Piecz łosoś z warzywami w piekarniku.',
        ingredients: ['Łosoś', 'Warzywa (np. brokuły, marchewka)', 'Przyprawy'],
        type: MealType.DINNER,
      },
      {
        title: 'Tortilla z Kurczakiem i Warzywami',
        description: 'Tortilla z grillowanym kurczakiem, warzywami i sosem.',
        kcal: 350,
        carbohydrates: 40,
        protein: 20,
        fat: 12,
        preparation: 'Zawijaj grillowanego kurczaka, warzywa i sos w tortilli.',
        ingredients: ['Tortilla', 'Kurczak', 'Warzywa (np. papryka, cebula)', 'Sos jogurtowy'],
        type: MealType.DINNER,
      },
      {
        title: 'Makaron z Warzywami i Serem',
        description: 'Makaron z warzywami i startym serem.',
        kcal: 450,
        carbohydrates: 60,
        protein: 15,
        fat: 18,
        preparation: 'Gotuj makaron, dodaj warzywa i posyp startym serem.',
        ingredients: ['Makaron', 'Warzywa (np. cukinia, pomidory)', 'Ser'],
        type: MealType.DINNER,
      },
      {
        title: 'Sałatka z Tuńczykiem',
        description: 'Sałatka z tuńczykiem, jajkiem i oliwkami.',
        kcal: 350,
        carbohydrates: 15,
        protein: 25,
        fat: 20,
        preparation: 'Wymieszaj składniki sałatki i dopraw.',
        ingredients: ['Tuńczyk', 'Jajka', 'Oliwki', 'Sałata', 'Sos winegret'],
        type: MealType.DINNER,
      },
    ],
  });

  console.log('Sample data has been added to the database.');
}
*/

import { PrismaClient, MealType } from '@prisma/client';

const prisma = new PrismaClient();

export async function main() {
    await prisma.meal.createMany({
        data: [
            // Śniadania
            {
                title: 'Pożywna Owsianka z Owocami',
                description: 'Klasyczna owsianka z dodatkiem świeżych owoców i orzechów.',
                kcal: 350,
                carbohydrates: 55,
                protein: 10,
                fat: 8,
                preparation: 'Gotuj płatki owsiane w mleku, dodaj pokrojone owoce i orzechy.',
                ingredients: ['Płatki owsiane', 'Mleko', 'Jagody', 'Banan', 'Orzechy', 'Miód'],
                type: MealType.BREAKFAST,
                image
            },
            {
                title: 'Jajecznica z Warzywami',
                description: 'Jajecznica z papryką, pomidorami i cebulą.',
                kcal: 300,
                carbohydrates: 15,
                protein: 20,
                fat: 18,
                preparation: 'Smaż jajka z pokrojonymi warzywami na patelni.',
                ingredients: ['Jaja', 'Papryka', 'Pomidory', 'Cebula', 'Oliwa z oliwek'],
                type: MealType.BREAKFAST,
            },
            {
                title: 'Smoothie Bananowo-Szpinakowe',
                description: 'Smoothie z banana i świeżego szpinaku.',
                kcal: 250,
                carbohydrates: 40,
                protein: 5,
                fat: 4,
                preparation: 'Blenduj banana, szpinak i jogurt naturalny.',
                ingredients: ['Banan', 'Szpinak', 'Jogurt naturalny'],
                type: MealType.BREAKFAST,
            },
            {
                title: 'Tosty z Awokado i Jajkiem',
                description: 'Tosty z pastą z awokado i gotowanym jajkiem.',
                kcal: 320,
                carbohydrates: 30,
                protein: 15,
                fat: 18,
                preparation: 'Posmaruj tosty pastą z awokado i dodaj pokrojone jajko.',
                ingredients: ['Chleb pełnoziarnisty', 'Awokado', 'Jajko', 'Sól', 'Pieprz'],
                type: MealType.BREAKFAST,
            },
            // Drugie Śniadania
            {
                title: 'Jogurt z Musli i Owocami',
                description: 'Jogurt naturalny z musli i świeżymi owocami.',
                kcal: 300,
                carbohydrates: 40,
                protein: 10,
                fat: 8,
                preparation: 'Wymieszaj jogurt z musli i dodaj pokrojone owoce.',
                ingredients: ['Jogurt naturalny', 'Musli', 'Owoce sezonowe'],
                type: MealType.SECOND_BREAKFAST,
            },
            {
                title: 'Kanapki z Chudą Wędliną i Warzywami',
                description: 'Kanapki z chudą wędliną, sałatą i pomidorami.',
                kcal: 280,
                carbohydrates: 35,
                protein: 15,
                fat: 10,
                preparation: 'Złóż wędlinę i warzywa między kromki chleba.',
                ingredients: ['Chleb pełnoziarnisty', 'Wędliny', 'Sałata', 'Pomidory', 'Ogórek'],
                type: MealType.SECOND_BREAKFAST,
            },
            {
                title: 'Sałatka Owocowa z Orzechami',
                description: 'Świeża sałatka owocowa z dodatkiem orzechów.',
                kcal: 250,
                carbohydrates: 35,
                protein: 5,
                fat: 12,
                preparation: 'Pokrój owoce i wymieszaj z orzechami.',
                ingredients: ['Owoce sezonowe', 'Orzechy'],
                type: MealType.SECOND_BREAKFAST,
            },
            {
                title: 'Chia Pudding z Owocami',
                description: 'Pudding chia z dodatkiem świeżych owoców.',
                kcal: 280,
                carbohydrates: 25,
                protein: 8,
                fat: 14,
                preparation: 'Wymieszaj nasiona chia z mlekiem i odstaw na kilka godzin, następnie dodaj owoce.',
                ingredients: ['Nasiona chia', 'Mleko', 'Owoce'],
                type: MealType.SECOND_BREAKFAST,
            },
            // Obiady
            {
                title: 'Kurczak w Sosie Pomidorowym z Ryżem',
                description: 'Soczysty kurczak w sosie pomidorowym podany z ryżem.',
                kcal: 450,
                carbohydrates: 60,
                protein: 35,
                fat: 12,
                preparation: 'Smaż kurczaka w sosie pomidorowym, podawaj z ugotowanym ryżem.',
                ingredients: ['Kurczak', 'Sos pomidorowy', 'Ryż', 'Przyprawy'],
                type: MealType.LUNCH,
            },
            {
                title: 'Sałatka Cezar z Kurczakiem',
                description: 'Klasyczna sałatka Cezar z grillowanym kurczakiem.',
                kcal: 400,
                carbohydrates: 20,
                protein: 30,
                fat: 22,
                preparation: 'Wymieszaj sałatę, kurczaka, grzanki i sos Cezar.',
                ingredients: ['Sałata', 'Grillowany kurczak', 'Grzanki', 'Sos Cezar'],
                type: MealType.LUNCH,
            },
            {
                title: 'Spaghetti Bolognese',
                description: 'Makaron spaghetti z klasycznym sosem bolognese.',
                kcal: 500,
                carbohydrates: 70,
                protein: 30,
                fat: 15,
                preparation: 'Gotuj makaron i sos bolognese, wymieszaj przed podaniem.',
                ingredients: ['Makaron spaghetti', 'Mięso mielone', 'Sos pomidorowy', 'Cebula', 'Przyprawy'],
                type: MealType.LUNCH,
            },
            {
                title: 'Kurczak Tandoori z Warzywami',
                description: 'Kurczak marynowany w przyprawach tandoori, pieczony z warzywami.',
                kcal: 450,
                carbohydrates: 25,
                protein: 35,
                fat: 20,
                preparation: 'Marynuj kurczaka w przyprawach tandoori, piecz z warzywami.',
                ingredients: ['Kurczak', 'Przyprawy tandoori', 'Warzywa (np. papryka, cukinia)'],
                type: MealType.LUNCH,
            },
            {
                title: 'Zupa Brokułowa z Grzankami',
                description: 'Kremowa zupa brokułowa podana z chrupiącymi grzankami.',
                kcal: 350,
                carbohydrates: 35,
                protein: 10,
                fat: 15,
                preparation: 'Gotuj brokuły, zmiksuj na krem, podawaj z grzankami.',
                ingredients: ['Brokuły', 'Cebula', 'Bulion', 'Grzanki'],
                type: MealType.LUNCH,
            },
            // Kolacje
            {
                title: 'Łosoś z Warzywami',
                description: 'Pieczony łosoś z mieszanką warzyw.',
                kcal: 400,
                carbohydrates: 20,
                protein: 30,
                fat: 20,
                preparation: 'Piecz łosoś z warzywami w piekarniku.',
                ingredients: ['Łosoś', 'Warzywa (np. brokuły, marchewka)', 'Przyprawy'],
                type: MealType.DINNER,
            },
            {
                title: 'Tortilla z Kurczakiem i Warzywami',
                description: 'Tortilla z grillowanym kurczakiem, warzywami i sosem.',
                kcal: 350,
                carbohydrates: 40,
                protein: 20,
                fat: 12,
                preparation: 'Zawijaj grillowanego kurczaka, warzywa i sos w tortilli.',
                ingredients: ['Tortilla', 'Kurczak', 'Warzywa (np. papryka, cebula)', 'Sos jogurtowy'],
                type: MealType.DINNER,
            },
            {
                title: 'Makaron z Warzywami i Serem',
                description: 'Makaron z warzywami i startym serem.',
                kcal: 450,
                carbohydrates: 60,
                protein: 15,
                fat: 18,
                preparation: 'Gotuj makaron, dodaj warzywa i posyp startym serem.',
                ingredients: ['Makaron', 'Warzywa (np. cukinia, pomidory)', 'Ser'],
                type: MealType.DINNER,
            },
            {
                title: 'Sałatka z Tuńczykiem',
                description: 'Sałatka z tuńczykiem, jajkiem i oliwkami.',
                kcal: 350,
                carbohydrates: 15,
                protein: 25,
                fat: 20,
                preparation: 'Wymieszaj składniki sałatki i dopraw.',
                ingredients: ['Tuńczyk', 'Jajka', 'Oliwki', 'Sałata', 'Sos winegret'],
                type: MealType.DINNER,
            },
        ],
    });

    console.log('Sample data has been added to the database.');
}
main()
    .catch(e => {
        console.error(e);
        process.exit(1);
    })
    .finally(async() => {
        await prisma.$disconnect();
    });


// Wywołanie funkcji