
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import { SessionProvider } from "next-auth/react";
import SessionProviderWrapper from "@/components/header/SessionProviderWrapper/SessionProviderWrapper";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import ReduxProvider from "@/components/Providers/ReduxProvider";


const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({subsets:["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
       <ReduxProvider>
        <SessionProviderWrapper>
        <Header />
        {children}
        </SessionProviderWrapper>
        </ReduxProvider>
        </body>
    </html>
  );
}
